type CodeToName = {
    [code: string]: string
}

const codes: CodeToName = {
    'af': 'Afrikaans',
    'af_na': 'Afrikaans (Namibia)',
    'af_za': 'Afrikaans (South Africa)',
    'agq': 'Aghem',
    'agq_cm': 'Aghem (Cameroon)',
    'ak': 'Akan',
    'ak_gh': 'Akan (Ghana)',
    'am': 'Amharic',
    'am_et': 'Amharic (Ethiopia)',
    'ar': 'Arabic',
    'ar_001': 'Arabic (World)',
    'ar_ae': 'Arabic (United Arab Emirates)',
    'ar_bh': 'Arabic (Bahrain)',
    'ar_dj': 'Arabic (Djibouti)',
    'ar_dz': 'Arabic (Algeria)',
    'ar_eg': 'Arabic (Egypt)',
    'ar_eh': 'Arabic (Western Sahara)',
    'ar_er': 'Arabic (Eritrea)',
    'ar_il': 'Arabic (Israel)',
    'ar_iq': 'Arabic (Iraq)',
    'ar_jo': 'Arabic (Jordan)',
    'ar_km': 'Arabic (Comoros)',
    'ar_kw': 'Arabic (Kuwait)',
    'ar_lb': 'Arabic (Lebanon)',
    'ar_ly': 'Arabic (Libya)',
    'ar_ma': 'Arabic (Morocco)',
    'ar_mr': 'Arabic (Mauritania)',
    'ar_om': 'Arabic (Oman)',
    'ar_ps': 'Arabic (Palestinian Territories)',
    'ar_qa': 'Arabic (Qatar)',
    'ar_sa': 'Arabic (Saudi Arabia)',
    'ar_sd': 'Arabic (Sudan)',
    'ar_so': 'Arabic (Somalia)',
    'ar_ss': 'Arabic (South Sudan)',
    'ar_sy': 'Arabic (Syria)',
    'ar_td': 'Arabic (Chad)',
    'ar_tn': 'Arabic (Tunisia)',
    'ar_ye': 'Arabic (Yemen)',
    'as': 'Assamese',
    'as_in': 'Assamese (India)',
    'asa': 'Asu',
    'asa_tz': 'Asu (Tanzania)',
    'ast': 'Asturian',
    'ast_es': 'Asturian (Spain)',
    'az': 'Azerbaijani',
    'az_cyrl': 'Azerbaijani (Cyrillic)',
    'az_cyrl_az': 'Azerbaijani (Cyrillic, Azerbaijan)',
    'az_latn': 'Azerbaijani (Latin)',
    'az_latn_az': 'Azerbaijani (Latin, Azerbaijan)',
    'bas': 'Basaa',
    'bas_cm': 'Basaa (Cameroon)',
    'be': 'Belarusian',
    'be_by': 'Belarusian (Belarus)',
    'bem': 'Bemba',
    'bem_zm': 'Bemba (Zambia)',
    'bez': 'Bena',
    'bez_tz': 'Bena (Tanzania)',
    'bg': 'Bulgarian',
    'bg_bg': 'Bulgarian (Bulgaria)',
    'bm': 'Bambara',
    'bm_ml': 'Bambara (Mali)',
    'bn': 'Bangla',
    'bn_bd': 'Bangla (Bangladesh)',
    'bn_in': 'Bangla (India)',
    'bo': 'Tibetan',
    'bo_cn': 'Tibetan (China)',
    'bo_in': 'Tibetan (India)',
    'br': 'Breton',
    'br_fr': 'Breton (France)',
    'brx': 'Bodo',
    'brx_in': 'Bodo (India)',
    'bs': 'Bosnian',
    'bs_cyrl': 'Bosnian (Cyrillic)',
    'bs_cyrl_ba': 'Bosnian (Cyrillic, Bosnia & Herzegovina)',
    'bs_latn': 'Bosnian (Latin)',
    'bs_latn_ba': 'Bosnian (Latin, Bosnia & Herzegovina)',
    'ca': 'Catalan',
    'ca_ad': 'Catalan (Andorra)',
    'ca_es': 'Catalan (Spain)',
    'ca_fr': 'Catalan (France)',
    'ca_it': 'Catalan (Italy)',
    'ccp': 'Chakma',
    'ccp_bd': 'Chakma (Bangladesh)',
    'ccp_in': 'Chakma (India)',
    'ce': 'Chechen',
    'ce_ru': 'Chechen (Russia)',
    'cgg': 'Chiga',
    'cgg_ug': 'Chiga (Uganda)',
    'chr': 'Cherokee',
    'chr_us': 'Cherokee (United States)',
    'ckb': 'Central Kurdish',
    'ckb_iq': 'Central Kurdish (Iraq)',
    'ckb_ir': 'Central Kurdish (Iran)',
    'cs': 'Czech',
    'cs_cz': 'Czech (Czechia)',
    'cy': 'Welsh',
    'cy_gb': 'Welsh (United Kingdom)',
    'da': 'Danish',
    'da_dk': 'Danish (Denmark)',
    'da_gl': 'Danish (Greenland)',
    'dav': 'Taita',
    'dav_ke': 'Taita (Kenya)',
    'de': 'German',
    'de_at': 'German (Austria)',
    'de_be': 'German (Belgium)',
    'de_ch': 'German (Switzerland)',
    'de_de': 'German (Germany)',
    'de_it': 'German (Italy)',
    'de_li': 'German (Liechtenstein)',
    'de_lu': 'German (Luxembourg)',
    'dje': 'Zarma',
    'dje_ne': 'Zarma (Niger)',
    'dsb': 'Lower Sorbian',
    'dsb_de': 'Lower Sorbian (Germany)',
    'dua': 'Duala',
    'dua_cm': 'Duala (Cameroon)',
    'dyo': 'Jola-Fonyi',
    'dyo_sn': 'Jola-Fonyi (Senegal)',
    'dz': 'Dzongkha',
    'dz_bt': 'Dzongkha (Bhutan)',
    'ebu': 'Embu',
    'ebu_ke': 'Embu (Kenya)',
    'ee': 'Ewe',
    'ee_gh': 'Ewe (Ghana)',
    'ee_tg': 'Ewe (Togo)',
    'el': 'Greek',
    'el_cy': 'Greek (Cyprus)',
    'el_gr': 'Greek (Greece)',
    'en': 'English',
    'en_001': 'English (World)',
    'en_150': 'English (Europe)',
    'en_ag': 'English (Antigua & Barbuda)',
    'en_ai': 'English (Anguilla)',
    'en_as': 'English (American Samoa)',
    'en_at': 'English (Austria)',
    'en_au': 'English (Australia)',
    'en_bb': 'English (Barbados)',
    'en_be': 'English (Belgium)',
    'en_bi': 'English (Burundi)',
    'en_bm': 'English (Bermuda)',
    'en_bs': 'English (Bahamas)',
    'en_bw': 'English (Botswana)',
    'en_bz': 'English (Belize)',
    'en_ca': 'English (Canada)',
    'en_cc': 'English (Cocos [Keeling] Islands)',
    'en_ch': 'English (Switzerland)',
    'en_ck': 'English (Cook Islands)',
    'en_cm': 'English (Cameroon)',
    'en_cx': 'English (Christmas Island)',
    'en_cy': 'English (Cyprus)',
    'en_de': 'English (Germany)',
    'en_dg': 'English (Diego Garcia)',
    'en_dk': 'English (Denmark)',
    'en_dm': 'English (Dominica)',
    'en_er': 'English (Eritrea)',
    'en_fi': 'English (Finland)',
    'en_fj': 'English (Fiji)',
    'en_fk': 'English (Falkland Islands)',
    'en_fm': 'English (Micronesia)',
    'en_gb': 'English (United Kingdom)',
    'en_gd': 'English (Grenada)',
    'en_gg': 'English (Guernsey)',
    'en_gh': 'English (Ghana)',
    'en_gi': 'English (Gibraltar)',
    'en_gm': 'English (Gambia)',
    'en_gu': 'English (Guam)',
    'en_gy': 'English (Guyana)',
    'en_hk': 'English (Hong Kong SAR China)',
    'en_ie': 'English (Ireland)',
    'en_il': 'English (Israel)',
    'en_im': 'English (Isle of Man)',
    'en_in': 'English (India)',
    'en_io': 'English (British Indian Ocean Territory)',
    'en_je': 'English (Jersey)',
    'en_jm': 'English (Jamaica)',
    'en_ke': 'English (Kenya)',
    'en_ki': 'English (Kiribati)',
    'en_kn': 'English (St Kitts & Nevis)',
    'en_ky': 'English (Cayman Islands)',
    'en_lc': 'English (St Lucia)',
    'en_lr': 'English (Liberia)',
    'en_ls': 'English (Lesotho)',
    'en_mg': 'English (Madagascar)',
    'en_mh': 'English (Marshall Islands)',
    'en_mo': 'English (Macau SAR China)',
    'en_mp': 'English (Northern Mariana Islands)',
    'en_ms': 'English (Montserrat)',
    'en_mt': 'English (Malta)',
    'en_mu': 'English (Mauritius)',
    'en_mw': 'English (Malawi)',
    'en_my': 'English (Malaysia)',
    'en_na': 'English (Namibia)',
    'en_nf': 'English (Norfolk Island)',
    'en_ng': 'English (Nigeria)',
    'en_nl': 'English (Netherlands)',
    'en_nr': 'English (Nauru)',
    'en_nu': 'English (Niue)',
    'en_nz': 'English (New Zealand)',
    'en_pg': 'English (Papua New Guinea)',
    'en_ph': 'English (Philippines)',
    'en_pk': 'English (Pakistan)',
    'en_pn': 'English (Pitcairn Islands)',
    'en_pr': 'English (Puerto Rico)',
    'en_pw': 'English (Palau)',
    'en_rw': 'English (Rwanda)',
    'en_sb': 'English (Solomon Islands)',
    'en_sc': 'English (Seychelles)',
    'en_sd': 'English (Sudan)',
    'en_se': 'English (Sweden)',
    'en_sg': 'English (Singapore)',
    'en_sh': 'English (St Helena)',
    'en_si': 'English (Slovenia)',
    'en_sl': 'English (Sierra Leone)',
    'en_ss': 'English (South Sudan)',
    'en_sx': 'English (Sint Maarten)',
    'en_sz': 'English (Swaziland)',
    'en_tc': 'English (Turks & Caicos Islands)',
    'en_tk': 'English (Tokelau)',
    'en_to': 'English (Tonga)',
    'en_tt': 'English (Trinidad & Tobago)',
    'en_tv': 'English (Tuvalu)',
    'en_tz': 'English (Tanzania)',
    'en_ug': 'English (Uganda)',
    'en_um': 'English (US Outlying Islands)',
    'en_us': 'English (United States)',
    'en_us_posix': 'English (United States, Computer)',
    'en_vc': 'English (St Vincent & Grenadines)',
    'en_vg': 'English (British Virgin Islands)',
    'en_vi': 'English (US Virgin Islands)',
    'en_vu': 'English (Vanuatu)',
    'en_ws': 'English (Samoa)',
    'en_za': 'English (South Africa)',
    'en_zm': 'English (Zambia)',
    'en_zw': 'English (Zimbabwe)',
    'eo': 'Esperanto',
    'es': 'Spanish',
    'es_419': 'Spanish (Latin America)',
    'es_ar': 'Spanish (Argentina)',
    'es_bo': 'Spanish (Bolivia)',
    'es_br': 'Spanish (Brazil)',
    'es_bz': 'Spanish (Belize)',
    'es_cl': 'Spanish (Chile)',
    'es_co': 'Spanish (Colombia)',
    'es_cr': 'Spanish (Costa Rica)',
    'es_cu': 'Spanish (Cuba)',
    'es_do': 'Spanish (Dominican Republic)',
    'es_ea': 'Spanish (Ceuta & Melilla)',
    'es_ec': 'Spanish (Ecuador)',
    'es_es': 'Spanish (Spain)',
    'es_gq': 'Spanish (Equatorial Guinea)',
    'es_gt': 'Spanish (Guatemala)',
    'es_hn': 'Spanish (Honduras)',
    'es_ic': 'Spanish (Canary Islands)',
    'es_mx': 'Spanish (Mexico)',
    'es_ni': 'Spanish (Nicaragua)',
    'es_pa': 'Spanish (Panama)',
    'es_pe': 'Spanish (Peru)',
    'es_ph': 'Spanish (Philippines)',
    'es_pr': 'Spanish (Puerto Rico)',
    'es_py': 'Spanish (Paraguay)',
    'es_sv': 'Spanish (El Salvador)',
    'es_us': 'Spanish (United States)',
    'es_uy': 'Spanish (Uruguay)',
    'es_ve': 'Spanish (Venezuela)',
    'et': 'Estonian',
    'et_ee': 'Estonian (Estonia)',
    'eu': 'Basque',
    'eu_es': 'Basque (Spain)',
    'ewo': 'Ewondo',
    'ewo_cm': 'Ewondo (Cameroon)',
    'fa': 'Persian',
    'fa_af': 'Persian (Afghanistan)',
    'fa_ir': 'Persian (Iran)',
    'ff': 'Fulah',
    'ff_cm': 'Fulah (Cameroon)',
    'ff_gn': 'Fulah (Guinea)',
    'ff_mr': 'Fulah (Mauritania)',
    'ff_sn': 'Fulah (Senegal)',
    'fi': 'Finnish',
    'fi_fi': 'Finnish (Finland)',
    'fil': 'Filipino',
    'fil_ph': 'Filipino (Philippines)',
    'fo': 'Faroese',
    'fo_dk': 'Faroese (Denmark)',
    'fo_fo': 'Faroese (Faroe Islands)',
    'fr': 'French',
    'fr_be': 'French (Belgium)',
    'fr_bf': 'French (Burkina Faso)',
    'fr_bi': 'French (Burundi)',
    'fr_bj': 'French (Benin)',
    'fr_bl': 'French (St Barthélemy)',
    'fr_ca': 'French (Canada)',
    'fr_cd': 'French (Congo - Kinshasa)',
    'fr_cf': 'French (Central African Republic)',
    'fr_cg': 'French (Congo - Brazzaville)',
    'fr_ch': 'French (Switzerland)',
    'fr_ci': 'French (Côte d’Ivoire)',
    'fr_cm': 'French (Cameroon)',
    'fr_dj': 'French (Djibouti)',
    'fr_dz': 'French (Algeria)',
    'fr_fr': 'French (France)',
    'fr_ga': 'French (Gabon)',
    'fr_gf': 'French (French Guiana)',
    'fr_gn': 'French (Guinea)',
    'fr_gp': 'French (Guadeloupe)',
    'fr_gq': 'French (Equatorial Guinea)',
    'fr_ht': 'French (Haiti)',
    'fr_km': 'French (Comoros)',
    'fr_lu': 'French (Luxembourg)',
    'fr_ma': 'French (Morocco)',
    'fr_mc': 'French (Monaco)',
    'fr_mf': 'French (St Martin)',
    'fr_mg': 'French (Madagascar)',
    'fr_ml': 'French (Mali)',
    'fr_mq': 'French (Martinique)',
    'fr_mr': 'French (Mauritania)',
    'fr_mu': 'French (Mauritius)',
    'fr_nc': 'French (New Caledonia)',
    'fr_ne': 'French (Niger)',
    'fr_pf': 'French (French Polynesia)',
    'fr_pm': 'French (St Pierre & Miquelon)',
    'fr_re': 'French (Réunion)',
    'fr_rw': 'French (Rwanda)',
    'fr_sc': 'French (Seychelles)',
    'fr_sn': 'French (Senegal)',
    'fr_sy': 'French (Syria)',
    'fr_td': 'French (Chad)',
    'fr_tg': 'French (Togo)',
    'fr_tn': 'French (Tunisia)',
    'fr_vu': 'French (Vanuatu)',
    'fr_wf': 'French (Wallis & Futuna)',
    'fr_yt': 'French (Mayotte)',
    'fur': 'Friulian',
    'fur_it': 'Friulian (Italy)',
    'fy': 'Western Frisian',
    'fy_nl': 'Western Frisian (Netherlands)',
    'ga': 'Irish',
    'ga_ie': 'Irish (Ireland)',
    'gd': 'Scottish Gaelic',
    'gd_gb': 'Scottish Gaelic (United Kingdom)',
    'gl': 'Galician',
    'gl_es': 'Galician (Spain)',
    'gsw': 'Swiss German',
    'gsw_ch': 'Swiss German (Switzerland)',
    'gsw_fr': 'Swiss German (France)',
    'gsw_li': 'Swiss German (Liechtenstein)',
    'gu': 'Gujarati',
    'gu_in': 'Gujarati (India)',
    'guz': 'Gusii',
    'guz_ke': 'Gusii (Kenya)',
    'gv': 'Manx',
    'gv_im': 'Manx (Isle of Man)',
    'ha': 'Hausa',
    'ha_gh': 'Hausa (Ghana)',
    'ha_ne': 'Hausa (Niger)',
    'ha_ng': 'Hausa (Nigeria)',
    'haw': 'Hawaiian',
    'haw_us': 'Hawaiian (United States)',
    'he': 'Hebrew',
    'he_il': 'Hebrew (Israel)',
    'hi': 'Hindi',
    'hi_in': 'Hindi (India)',
    'hr': 'Croatian',
    'hr_ba': 'Croatian (Bosnia & Herzegovina)',
    'hr_hr': 'Croatian (Croatia)',
    'hsb': 'Upper Sorbian',
    'hsb_de': 'Upper Sorbian (Germany)',
    'hu': 'Hungarian',
    'hu_hu': 'Hungarian (Hungary)',
    'hy': 'Armenian',
    'hy_am': 'Armenian (Armenia)',
    'id': 'Indonesian',
    'id_id': 'Indonesian (Indonesia)',
    'ig': 'Igbo',
    'ig_ng': 'Igbo (Nigeria)',
    'ii': 'Sichuan Yi',
    'ii_cn': 'Sichuan Yi (China)',
    'is': 'Icelandic',
    'is_is': 'Icelandic (Iceland)',
    'it': 'Italian',
    'it_ch': 'Italian (Switzerland)',
    'it_it': 'Italian (Italy)',
    'it_sm': 'Italian (San Marino)',
    'it_va': 'Italian (Vatican City)',
    'ja': 'Japanese',
    'ja_jp': 'Japanese (Japan)',
    'jgo': 'Ngomba',
    'jgo_cm': 'Ngomba (Cameroon)',
    'jmc': 'Machame',
    'jmc_tz': 'Machame (Tanzania)',
    'ka': 'Georgian',
    'ka_ge': 'Georgian (Georgia)',
    'kab': 'Kabyle',
    'kab_dz': 'Kabyle (Algeria)',
    'kam': 'Kamba',
    'kam_ke': 'Kamba (Kenya)',
    'kde': 'Makonde',
    'kde_tz': 'Makonde (Tanzania)',
    'kea': 'Kabuverdianu',
    'kea_cv': 'Kabuverdianu (Cape Verde)',
    'khq': 'Koyra Chiini',
    'khq_ml': 'Koyra Chiini (Mali)',
    'ki': 'Kikuyu',
    'ki_ke': 'Kikuyu (Kenya)',
    'kk': 'Kazakh',
    'kk_kz': 'Kazakh (Kazakhstan)',
    'kkj': 'Kako',
    'kkj_cm': 'Kako (Cameroon)',
    'kl': 'Kalaallisut',
    'kl_gl': 'Kalaallisut (Greenland)',
    'kln': 'Kalenjin',
    'kln_ke': 'Kalenjin (Kenya)',
    'km': 'Khmer',
    'km_kh': 'Khmer (Cambodia)',
    'kn': 'Kannada',
    'kn_in': 'Kannada (India)',
    'ko': 'Korean',
    'ko_kp': 'Korean (North Korea)',
    'ko_kr': 'Korean (South Korea)',
    'kok': 'Konkani',
    'kok_in': 'Konkani (India)',
    'ks': 'Kashmiri',
    'ks_in': 'Kashmiri (India)',
    'ksb': 'Shambala',
    'ksb_tz': 'Shambala (Tanzania)',
    'ksf': 'Bafia',
    'ksf_cm': 'Bafia (Cameroon)',
    'ksh': 'Colognian',
    'ksh_de': 'Colognian (Germany)',
    'kw': 'Cornish',
    'kw_gb': 'Cornish (United Kingdom)',
    'ky': 'Kyrgyz',
    'ky_kg': 'Kyrgyz (Kyrgyzstan)',
    'lag': 'Langi',
    'lag_tz': 'Langi (Tanzania)',
    'lb': 'Luxembourgish',
    'lb_lu': 'Luxembourgish (Luxembourg)',
    'lg': 'Ganda',
    'lg_ug': 'Ganda (Uganda)',
    'lkt': 'Lakota',
    'lkt_us': 'Lakota (United States)',
    'ln': 'Lingala',
    'ln_ao': 'Lingala (Angola)',
    'ln_cd': 'Lingala (Congo - Kinshasa)',
    'ln_cf': 'Lingala (Central African Republic)',
    'ln_cg': 'Lingala (Congo - Brazzaville)',
    'lo': 'Lao',
    'lo_la': 'Lao (Laos)',
    'lrc': 'Northern Luri',
    'lrc_iq': 'Northern Luri (Iraq)',
    'lrc_ir': 'Northern Luri (Iran)',
    'lt': 'Lithuanian',
    'lt_lt': 'Lithuanian (Lithuania)',
    'lu': 'Luba-Katanga',
    'lu_cd': 'Luba-Katanga (Congo - Kinshasa)',
    'luo': 'Luo',
    'luo_ke': 'Luo (Kenya)',
    'luy': 'Luyia',
    'luy_ke': 'Luyia (Kenya)',
    'lv': 'Latvian',
    'lv_lv': 'Latvian (Latvia)',
    'mas': 'Masai',
    'mas_ke': 'Masai (Kenya)',
    'mas_tz': 'Masai (Tanzania)',
    'mer': 'Meru',
    'mer_ke': 'Meru (Kenya)',
    'mfe': 'Morisyen',
    'mfe_mu': 'Morisyen (Mauritius)',
    'mg': 'Malagasy',
    'mg_mg': 'Malagasy (Madagascar)',
    'mgh': 'Makhuwa-Meetto',
    'mgh_mz': 'Makhuwa-Meetto (Mozambique)',
    'mgo': 'Metaʼ',
    'mgo_cm': 'Metaʼ (Cameroon)',
    'mk': 'Macedonian',
    'mk_mk': 'Macedonian (Macedonia)',
    'ml': 'Malayalam',
    'ml_in': 'Malayalam (India)',
    'mn': 'Mongolian',
    'mn_mn': 'Mongolian (Mongolia)',
    'mr': 'Marathi',
    'mr_in': 'Marathi (India)',
    'ms': 'Malay',
    'ms_bn': 'Malay (Brunei)',
    'ms_my': 'Malay (Malaysia)',
    'ms_sg': 'Malay (Singapore)',
    'mt': 'Maltese',
    'mt_mt': 'Maltese (Malta)',
    'mua': 'Mundang',
    'mua_cm': 'Mundang (Cameroon)',
    'my': 'Burmese',
    'my_mm': 'Burmese (Myanmar [Burma])',
    'mzn': 'Mazanderani',
    'mzn_ir': 'Mazanderani (Iran)',
    'naq': 'Nama',
    'naq_na': 'Nama (Namibia)',
    'nb': 'Norwegian Bokmål',
    'nb_no': 'Norwegian Bokmål (Norway)',
    'nb_sj': 'Norwegian Bokmål (Svalbard & Jan Mayen)',
    'nd': 'North Ndebele',
    'nd_zw': 'North Ndebele (Zimbabwe)',
    'nds': 'Low German',
    'nds_de': 'Low German (Germany)',
    'nds_nl': 'Low German (Netherlands)',
    'ne': 'Nepali',
    'ne_in': 'Nepali (India)',
    'ne_np': 'Nepali (Nepal)',
    'nl': 'Dutch',
    'nl_aw': 'Dutch (Aruba)',
    'nl_be': 'Dutch (Belgium)',
    'nl_bq': 'Dutch (Caribbean Netherlands)',
    'nl_cw': 'Dutch (Curaçao)',
    'nl_nl': 'Dutch (Netherlands)',
    'nl_sr': 'Dutch (Suriname)',
    'nl_sx': 'Dutch (Sint Maarten)',
    'nmg': 'Kwasio',
    'nmg_cm': 'Kwasio (Cameroon)',
    'nn': 'Norwegian Nynorsk',
    'nn_no': 'Norwegian Nynorsk (Norway)',
    'nnh': 'Ngiemboon',
    'nnh_cm': 'Ngiemboon (Cameroon)',
    'no': 'Norwegian',
    'nus': 'Nuer',
    'nus_ss': 'Nuer (South Sudan)',
    'nyn': 'Nyankole',
    'nyn_ug': 'Nyankole (Uganda)',
    'om': 'Oromo',
    'om_et': 'Oromo (Ethiopia)',
    'om_ke': 'Oromo (Kenya)',
    'or': 'Odia',
    'or_in': 'Odia (India)',
    'os': 'Ossetic',
    'os_ge': 'Ossetic (Georgia)',
    'os_ru': 'Ossetic (Russia)',
    'pa': 'Punjabi',
    'pa_arab': 'Punjabi (Arabic)',
    'pa_arab_pk': 'Punjabi (Arabic, Pakistan)',
    'pa_guru': 'Punjabi (Gurmukhi)',
    'pa_guru_in': 'Punjabi (Gurmukhi, India)',
    'pl': 'Polish',
    'pl_pl': 'Polish (Poland)',
    'ps': 'Pashto',
    'ps_af': 'Pashto (Afghanistan)',
    'pt': 'Portuguese',
    'pt_ao': 'Portuguese (Angola)',
    'pt_br': 'Portuguese (Brazil)',
    'pt_ch': 'Portuguese (Switzerland)',
    'pt_cv': 'Portuguese (Cape Verde)',
    'pt_gq': 'Portuguese (Equatorial Guinea)',
    'pt_gw': 'Portuguese (Guinea-Bissau)',
    'pt_lu': 'Portuguese (Luxembourg)',
    'pt_mo': 'Portuguese (Macau SAR China)',
    'pt_mz': 'Portuguese (Mozambique)',
    'pt_pt': 'Portuguese (Portugal)',
    'pt_st': 'Portuguese (São Tomé & Príncipe)',
    'pt_tl': 'Portuguese (Timor-Leste)',
    'qu': 'Quechua',
    'qu_bo': 'Quechua (Bolivia)',
    'qu_ec': 'Quechua (Ecuador)',
    'qu_pe': 'Quechua (Peru)',
    'rm': 'Romansh',
    'rm_ch': 'Romansh (Switzerland)',
    'rn': 'Rundi',
    'rn_bi': 'Rundi (Burundi)',
    'ro': 'Romanian',
    'ro_md': 'Romanian (Moldova)',
    'ro_ro': 'Romanian (Romania)',
    'rof': 'Rombo',
    'rof_tz': 'Rombo (Tanzania)',
    'ru': 'Russian',
    'ru_by': 'Russian (Belarus)',
    'ru_kg': 'Russian (Kyrgyzstan)',
    'ru_kz': 'Russian (Kazakhstan)',
    'ru_md': 'Russian (Moldova)',
    'ru_ru': 'Russian (Russia)',
    'ru_ua': 'Russian (Ukraine)',
    'rw': 'Kinyarwanda',
    'rw_rw': 'Kinyarwanda (Rwanda)',
    'rwk': 'Rwa',
    'rwk_tz': 'Rwa (Tanzania)',
    'sah': 'Sakha',
    'sah_ru': 'Sakha (Russia)',
    'saq': 'Samburu',
    'saq_ke': 'Samburu (Kenya)',
    'sbp': 'Sangu',
    'sbp_tz': 'Sangu (Tanzania)',
    'se': 'Northern Sami',
    'se_fi': 'Northern Sami (Finland)',
    'se_no': 'Northern Sami (Norway)',
    'se_se': 'Northern Sami (Sweden)',
    'seh': 'Sena',
    'seh_mz': 'Sena (Mozambique)',
    'ses': 'Koyraboro Senni',
    'ses_ml': 'Koyraboro Senni (Mali)',
    'sg': 'Sango',
    'sg_cf': 'Sango (Central African Republic)',
    'shi': 'Tachelhit',
    'shi_latn': 'Tachelhit (Latin)',
    'shi_latn_ma': 'Tachelhit (Latin, Morocco)',
    'shi_tfng': 'Tachelhit (Tifinagh)',
    'shi_tfng_ma': 'Tachelhit (Tifinagh, Morocco)',
    'si': 'Sinhala',
    'si_lk': 'Sinhala (Sri Lanka)',
    'sk': 'Slovak',
    'sk_sk': 'Slovak (Slovakia)',
    'sl': 'Slovenian',
    'sl_si': 'Slovenian (Slovenia)',
    'smn': 'Inari Sami',
    'smn_fi': 'Inari Sami (Finland)',
    'sn': 'Shona',
    'sn_zw': 'Shona (Zimbabwe)',
    'so': 'Somali',
    'so_dj': 'Somali (Djibouti)',
    'so_et': 'Somali (Ethiopia)',
    'so_ke': 'Somali (Kenya)',
    'so_so': 'Somali (Somalia)',
    'sq': 'Albanian',
    'sq_al': 'Albanian (Albania)',
    'sq_mk': 'Albanian (Macedonia)',
    'sq_xk': 'Albanian (Kosovo)',
    'sr': 'Serbian',
    'sr_cyrl': 'Serbian (Cyrillic)',
    'sr_cyrl_ba': 'Serbian (Cyrillic, Bosnia & Herzegovina)',
    'sr_cyrl_me': 'Serbian (Cyrillic, Montenegro)',
    'sr_cyrl_rs': 'Serbian (Cyrillic, Serbia)',
    'sr_cyrl_xk': 'Serbian (Cyrillic, Kosovo)',
    'sr_latn': 'Serbian (Latin)',
    'sr_latn_ba': 'Serbian (Latin, Bosnia & Herzegovina)',
    'sr_latn_me': 'Serbian (Latin, Montenegro)',
    'sr_latn_rs': 'Serbian (Latin, Serbia)',
    'sr_latn_xk': 'Serbian (Latin, Kosovo)',
    'sv': 'Swedish',
    'sv_ax': 'Swedish (Åland Islands)',
    'sv_fi': 'Swedish (Finland)',
    'sv_se': 'Swedish (Sweden)',
    'sw': 'Swahili',
    'sw_cd': 'Swahili (Congo - Kinshasa)',
    'sw_ke': 'Swahili (Kenya)',
    'sw_tz': 'Swahili (Tanzania)',
    'sw_ug': 'Swahili (Uganda)',
    'ta': 'Tamil',
    'ta_in': 'Tamil (India)',
    'ta_lk': 'Tamil (Sri Lanka)',
    'ta_my': 'Tamil (Malaysia)',
    'ta_sg': 'Tamil (Singapore)',
    'te': 'Telugu',
    'te_in': 'Telugu (India)',
    'teo': 'Teso',
    'teo_ke': 'Teso (Kenya)',
    'teo_ug': 'Teso (Uganda)',
    'tg': 'Tajik',
    'tg_tj': 'Tajik (Tajikistan)',
    'th': 'Thai',
    'th_th': 'Thai (Thailand)',
    'ti': 'Tigrinya',
    'ti_er': 'Tigrinya (Eritrea)',
    'ti_et': 'Tigrinya (Ethiopia)',
    'to': 'Tongan',
    'to_to': 'Tongan (Tonga)',
    'tr': 'Turkish',
    'tr_cy': 'Turkish (Cyprus)',
    'tr_tr': 'Turkish (Turkey)',
    'tt': 'Tatar',
    'tt_ru': 'Tatar (Russia)',
    'twq': 'Tasawaq',
    'twq_ne': 'Tasawaq (Niger)',
    'tzm': 'Central Atlas Tamazight',
    'tzm_ma': 'Central Atlas Tamazight (Morocco)',
    'ug': 'Uyghur',
    'ug_cn': 'Uyghur (China)',
    'uk': 'Ukrainian',
    'uk_ua': 'Ukrainian (Ukraine)',
    'ur': 'Urdu',
    'ur_in': 'Urdu (India)',
    'ur_pk': 'Urdu (Pakistan)',
    'uz': 'Uzbek',
    'uz_arab': 'Uzbek (Arabic)',
    'uz_arab_af': 'Uzbek (Arabic, Afghanistan)',
    'uz_cyrl': 'Uzbek (Cyrillic)',
    'uz_cyrl_uz': 'Uzbek (Cyrillic, Uzbekistan)',
    'uz_latn': 'Uzbek (Latin)',
    'uz_latn_uz': 'Uzbek (Latin, Uzbekistan)',
    'vai': 'Vai',
    'vai_latn': 'Vai (Latin)',
    'vai_latn_lr': 'Vai (Latin, Liberia)',
    'vai_vaii': 'Vai (Vai)',
    'vai_vaii_lr': 'Vai (Vai, Liberia)',
    'vi': 'Vietnamese',
    'vi_vn': 'Vietnamese (Vietnam)',
    'vun': 'Vunjo',
    'vun_tz': 'Vunjo (Tanzania)',
    'wae': 'Walser',
    'wae_ch': 'Walser (Switzerland)',
    'wo': 'Wolof',
    'wo_sn': 'Wolof (Senegal)',
    'xog': 'Soga',
    'xog_ug': 'Soga (Uganda)',
    'yav': 'Yangben',
    'yav_cm': 'Yangben (Cameroon)',
    'yi': 'Yiddish',
    'yi_001': 'Yiddish (World)',
    'yo': 'Yoruba',
    'yo_bj': 'Yoruba (Benin)',
    'yo_ng': 'Yoruba (Nigeria)',
    'yue': 'Cantonese',
    'yue_hans': 'Cantonese (Simplified)',
    'yue_hans_cn': 'Cantonese (Simplified, China)',
    'yue_hant': 'Cantonese (Traditional)',
    'yue_hant_hk': 'Cantonese (Traditional, Hong Kong SAR China)',
    'zgh': 'Standard Moroccan Tamazight',
    'zgh_ma': 'Standard Moroccan Tamazight (Morocco)',
    'zh': 'Chinese',
    'zh_cn': 'Chinese (Simplified, China)',
    'zh_hans': 'Chinese (Simplified)',
    'zh_hans_cn': 'Chinese (Simplified, China)',
    'zh_hans_hk': 'Chinese (Simplified, Hong Kong SAR China)',
    'zh_hans_mo': 'Chinese (Simplified, Macau SAR China)',
    'zh_hans_sg': 'Chinese (Simplified, Singapore)',
    'zh_hant': 'Chinese (Traditional)',
    'zh_hant_hk': 'Chinese (Traditional, Hong Kong SAR China)',
    'zh_hant_mo': 'Chinese (Traditional, Macau SAR China)',
    'zh_hant_tw': 'Chinese (Traditional, Taiwan)',
    'zh_tw': 'Chinese (Traditional, Taiwan)',
    'zu': 'Zulu',
    'zu_za': 'Zulu (South Africa)'
}

export default function findName(code: string): string {
    const translated = codes[code.toLowerCase()];

    return translated === undefined ? code : translated;
}
